# Generated by Django 5.0.7 on 2024-08-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('black', 'Black')], max_length=20)),
                ('body', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('ACTION', 'Action'), ('WILD', 'Wild')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('hands', models.ManyToManyField(blank=True, related_name='players', to='uno_game.card')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ManyToManyField(blank=True, to='uno_game.card')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField(default=0)),
                ('direction', models.BooleanField(default=True)),
                ('deck', models.ManyToManyField(related_name='deck_cards', to='uno_game.card')),
                ('current_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_games', to='uno_game.player')),
                ('players', models.ManyToManyField(to='uno_game.player')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uno_game.table')),
            ],
        ),
    ]
